services:
  blaise-server:
    image: vincentbrodin/blaise:latest
    container_name: blaise-server
    ports:
      - "3000:3000"
    environment:
      - GTFS_DATA_PATH=/app/data/GTFS.zip
    volumes:
      - ./gtfs_data:/app/data
    restart: unless-stopped
